### ISSUE TITLE
it's there any plans to write a browser version?

### ISSUE THREAD

**Issue by hugoruscitti** [timothycrosley/jiphy#21]
Hi!, i'm looking for a jiphy version that can run in a javascript browser, i think it would be great convert python to javascript and javascript to python without server side.

Do you have some ideas to make some like that?

**Comment by Lexcon** [comment]
I believe there exists a javascript engine to run python code in the browser. Did you Google this ? 


Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: Hugo Ruscitti <notifications@github.com> 
Datum: 24-11-16  01:49  (GMT+01:00) 
Aan: timothycrosley/jiphy <jiphy@noreply.github.com> 
Onderwerp: [timothycrosley/jiphy] it's there any plans to write a browser
  version? (#21) 

Hi!, i'm looking for a jiphy version that can run in a javascript browser, i think it would be great convert python to javascript and javascript to python without server side.
Do you have some ideas to make some like that?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/timothycrosley/jiphy","title":"timothycrosley/jiphy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/timothycrosley/jiphy"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"it's there any plans to write a browser version? (#21)"}],"action":{"name":"View Issue","url":"https://github.com/timothycrosley/jiphy/issues/21"}}}

**Comment by Lexcon** [comment]
http://www.skulpt.org/#

http://pypyjs.org/

**Comment by hugoruscitti** [comment]
Thanks @Lexcon, http://www.rapydscript.com/ seems to be good too. But all these alternatives lack bi-directional conversion that jimphy has :(

I think it's a unique feature ...

**Comment by Lexcon** [comment]
When you have python-to-javascript, you can run a python module to run 
javascript-to-python to go back and forth language wise.

Js2Py is a pretty awesome tool that can do that, it runs about any 
javascript in the CPython engine.

Robert

**Comment by hugoruscitti** [comment]
Thank!
